contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

baseurl = "https://velovix.github.io/"
languageCode = "en-us"
title = "velovix"
canonifyurls = true

[author]
	name = "Tyler Compton"
	github = "velovix"
